version: 2.1
jobs:
  contrast-verify:
    executor: contrastsecurity/default
    steps:
    - checkout
    - contrastsecurity/check-vulnerabilities:
        severities: MEDIUM 
        org-id: 0b4acb35-f2b2-4d20-a392-25bcf9eae0cb
        application-id: 0160b2bf-520a-40b0-b090-bdd8322e2b02
        contrast-url: https://apptwo.contrastsecurity.com/Contrast

orbs:
  contrastsecurity: contrastsecurity/verify@0.1.2
workflows:
  test:
    jobs:
    - contrast-verify